#!/usr/bin/with-contenv bash

umask 0002

chown -R bytesized:bytesized /app /config

cd /app/plex-requests

echo "Starting Plex Requests.. This can take a while.. Make some coffee."
exec s6-setuidgid bytesized meteor
